# Generated by Django 3.0.1 on 2020-02-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200130_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='post_type',
            field=models.CharField(choices=[('公告', 'new'), ('分享', 'share'), ('資訊', 'info'), ('練習', 'practice'), ('問題', 'problem'), ('其他', 'other')], default='share', max_length=30),
        ),
    ]
