# Generated by Django 3.0.1 on 2020-02-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200206_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='post_typel',
            field=models.CharField(choices=[('new', '公告'), ('share', '分享'), ('info', '資訊'), ('practice', '練習'), ('problem', '問題'), ('other', '其他')], default='new', max_length=30),
        ),
    ]
